### PR TITLE
Update definitions of flag items

### PR DESCRIPTION
**Pull request by vaitkus**
This PR updates all flag definitions to be more similar to the ones in `CIF_CORE`. The flag values are made case-sensitive, and are explicitly assigned the `State` purpose and `Assigned` source.

Note, that the assigned purpose and source values differ from the default ones, therefore this might conflict with PR #46.

### CODE REVIEW

**Comment by jamesrhester** [comment]
This might be a bit difficult to change as software authors may already read or write these flags in a case-insensitive way. I'd suggest we leave these alone.

**Comment by vaitkus** [comment]
Oh, I did not see the dictionary did not originate as DDL1 (which would somewhat require it to be case-sensitive for compatibility purposes). However, given that all enumeration values in `CIF_CORE` are case-sensitive, it would make sense to change it here as well just to be consistent. Maybe we should ask if developers are OK with this change (as suggested in comments of issue #50) or is this particular issue not worth the bother?

**Comment by brantonc** [comment]
I have no opinion on this matter.

**Comment by jamesrhester** [comment]
To resolve properly would require polling the software developers and/or finding examples in the wild of the use of these tags. I've checked CrysFML and CrysFML2008 (underlying code for FullProf) and the latter reads in two of these datanames, but does not yet use the values, and doesn't output them. GSASII does not refer to these anywhere either. Jana code not available. Given that they don't seem widely used yet, happy to merge these changes.

**Review by jamesrhester — APPROVED** [review]

**Pull request merged**
